version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_orderline_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_orderline_data:/var/lib/postgresql/data
    networks:
      - local_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 5

  backend:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: razmaz112/orderline-backend:latest
    container_name: orderline_fastapi_app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8003:8000"
    volumes:
      - .:/app
    networks:
      - local_network

volumes:
  postgres_orderline_data:

networks:
  local_network:
    driver: bridge